# Generated by Django 2.2.2 on 2020-01-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=True),
        ),
    ]
